/**
 * build-cmudict.js — compile CMUdict text format to runtime JSON,
 * optionally folding in Phonetisaurus alignments for phase 2+.
 *
 * Run: node scripts/build-cmudict.js [INPUT.txt] [OUTPUT.json]
 *
 * Defaults:
 *   INPUT  = data/cmudict.txt if exists, else data/cmudict-sample.txt
 *   OUTPUT = data/cmudict.json
 *
 * Alignment input is picked automatically from the corresponding .corpus:
 *   data/cmudict.txt        ↔ data/aligned-cmudict.corpus
 *   data/cmudict-sample.txt ↔ data/cmudict-sample.corpus
 *
 * The full corpus is generated by `npm run align-cmudict`. The sample
 * corpus is checked in (extracted once from a full alignment).
 *
 * If the alignment file is missing, the dictionary still builds but
 * entries lack `pairs` — phase 2+ rules cannot fire on those entries.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDictionaryData } from '../src/dictionary.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

const FULL = path.join(ROOT, 'data', 'cmudict.txt');
const SAMPLE = path.join(ROOT, 'data', 'cmudict-sample.txt');
const FULL_ALIGNED = path.join(ROOT, 'data', 'aligned-cmudict.corpus');
const SAMPLE_ALIGNED = path.join(ROOT, 'data', 'cmudict-sample.corpus');
const DEFAULT_OUTPUT = path.join(ROOT, 'data', 'cmudict.json');

const inputPath = process.argv[2] ||
  (fs.existsSync(FULL) ? FULL : SAMPLE);
const outputPath = process.argv[3] || DEFAULT_OUTPUT;

if (!fs.existsSync(inputPath)) {
  console.error(`Input not found: ${inputPath}`);
  console.error('Run `npm run fetch-cmudict` to download the full dictionary.');
  process.exit(1);
}

const usingSample = inputPath === SAMPLE;
const alignedPath = usingSample ? SAMPLE_ALIGNED : FULL_ALIGNED;
const alignedText = fs.existsSync(alignedPath)
  ? fs.readFileSync(alignedPath, 'utf-8')
  : null;

console.log(`Building dictionary from ${path.basename(inputPath)}...`);
if (alignedText) {
  console.log(`  with alignment from ${path.basename(alignedPath)}`);
} else {
  console.log(`  (no alignment found at ${path.basename(alignedPath)} — phase 2+ rules will not fire)`);
}
const text = fs.readFileSync(inputPath, 'utf-8');
const data = buildDictionaryData(text, alignedText);

fs.writeFileSync(outputPath, JSON.stringify(data));
const wordCount = Object.keys(data.entries).length;
const alignedCount = Object.values(data.entries)
  .reduce((acc, prons) => acc + prons.filter((p) => p.pairs).length, 0);
const totalProns = Object.values(data.entries)
  .reduce((acc, prons) => acc + prons.length, 0);
console.log(`Wrote ${outputPath}`);
console.log(`  ${wordCount.toLocaleString()} unique word(s)`);
console.log(`  ${alignedCount.toLocaleString()} / ${totalProns.toLocaleString()} pronunciations have alignment`);
if (usingSample) {
  console.log('');
  console.log('NOTE: this is the small sample dictionary. For real use, run:');
  console.log('  npm run fetch-cmudict');
  console.log('  npm run align-cmudict');
  console.log('  npm run build');
}
